### ISSUE TITLE
TODO checklist for 2022

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaLocationUtils#31]
Items as they come up:

-----
_TODO:_

----
_Items finished on 2022-09-21_

- [x] Update `location_getSingleElevation_USGS` to new web service. (9/21)

----
_Items finished on 2022-08-10_

- [x] Documentation for `location_getSingleElevation_USGS()` should mention "meters" or allow requesting either m or ft (5/05)

----
_Items finished on 2022-07-14_

- [x] Improve documentation and examples for `table_updateColumn()`. (7/14)
- [x] `table_updateColumn()` should handle `Error in locationTbl[[columnName]][recordIndex] <- locationData : 
  NAs are not allowed in subscripted assignments`. (7/14)

----
_Items finished on 2022-05-06_
- [x] add `table_getDistances()` to return ordered distances from a target location; `table_getNearestDistance()` should be described better and have use cases to explain the difference (5/06)
