### ISSUE TITLE
TODO checklis

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaLocationUtils#32]
Items as they come up:

-----
_TODO:_

- [ ] Add `location_initializeExisting()` to skip spatial searches if not needed. (10/25/23)
- [ ] test performance of `table_addClustering()` when there are 150 clusters of 2/3/4 locations each. (10/30/23)

----
_Items finished by 2026-04-19_

- [x] updated documentation to use **roxygen2** 7.3.x syntax (04/19/26)
- [x] `table_save()` should allow for `csv.gz` (11/25/24)
- [x] limit `maxClusters` to `now(tbl)` in `clusterByDistance.R` (08/14/24)

----
_Items finished by 2024-01-23_

- [x] Update USGS elevation service URL ([docs](https://epqs.nationalmap.gov/v1/docs)). (01/22/24)

----
_Items finished by 2023-11-13_

- [x] `table_getNearestLocation()` doesn't guarantee a single record per incoming location because `dplyr::left_join()` doesn't guarantee that. We either need an error message or some first-encountered logic with adequate documentation and a warning message. (11/13/23)
- [x] `table_save()` should allow `output_type` to be a vector of types. (11/02/23)
- [x] use `precision` argument in call to `MazamaCoreUtils::createLocationID()`. (11/13/23)

----
_Items finished by 2023-10-24_

- [x] add `postalCode` to the core metadata and deprecate `zip` (10/24/23)

----
_Items finished by 2022-08-29_

- [x] Add `algorithm` argument to `location_createID()`.
